### ISSUE TITLE
Error when viewing overview for spring training games

### ISSUE THREAD

**Issue by KYDronePilot** [panzarino/mlbgame#121]
I'm getting an error when trying to view the scoreboard for spring training games. Here is the error:

```
>>> mlbgame.overview('2019_03_10_chnmlb_milmlb_1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/mlbgame/__init__.py", line 198, in overview
    return mlbgame.game.Overview(mlbgame.game.overview(game_id))
  File "/usr/local/lib/python3.7/site-packages/mlbgame/game.py", line 328, in overview
    raw_box_score_root = etree.parse(raw_box_score).getroot()
  File "src/lxml/etree.pyx", line 3435, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1861, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1881, in lxml.etree._parseFilelikeDocument
  File "src/lxml/parser.pxi", line 1776, in lxml.etree._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 1187, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "http://gd2.mlb.com/components/game/mlb/year_2019/month_03/day_10/gid_2019_03_10_chnmlb_milmlb_1/rawboxscore.xml", line 1
lxml.etree.XMLSyntaxError: Space required after the Public Identifier, line 1, column 55
```

Is this due to MLB not posting scoreboard details for spring training games or is this an issue with the library?

**Comment by trevor-viljoen** [comment]
rawbowscore.xml doesn’t exist in this case. Spring training is never uniform in what data is available and where it is found. There are always some weird one-offs that throw the code for a loop.

**Comment by ajbowler** [comment]
This was fixed and merged into master via #119 we just need a new tag

**Comment by KYDronePilot** [comment]
Ah, I see. What do you mean by a new tag? A new version on PyPi?

**Comment by ajbowler** [comment]
Yes

**Comment by panzarino** [comment]
Yep, there should be a new release coming this week when I get the chance.

**Comment by jacobmh1177** [comment]
This bug appears to be fixed for the game overview but is still present for player stats:

```
>>> games = mlb.combine_games( mlb.games(2019, 3, 29))
>>> print(games[0])
Tigers (0) at Blue Jays (6)
>>> mlb.player_stats(games[0].game_id)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/mlbgame/mlbgame/__init__.py", line 214, in player_stats
    data = mlbgame.stats.player_stats(game_id)
  File "/home/ec2-user/mlbgame/mlbgame/stats.py", line 75, in player_stats
    raw_box_score_tree = etree.parse(raw_box_score).getroot()
  File "src/lxml/etree.pyx", line 3435, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1861, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1881, in lxml.etree._parseFilelikeDocument
  File "src/lxml/parser.pxi", line 1776, in lxml.etree._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 1187, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "http://gd2.mlb.com/components/game/mlb/year_2019/month_03/day_29/gid_2019_03_29_detmlb_tormlb_1/rawboxscore.xml", line 1
lxml.etree.XMLSyntaxError: Space required after the Public Identifier, line 1, column 55
>>> 
```

**Comment by panzarino** [comment]
@jacobmh1177 Please submit a new issue for this bug relating to player stats.

**Comment by KYDronePilot** [comment]
When can we expect a new release that includes a fix for the original issue? I am working on a project that uses this library, but am having to manually install the `master` branch to get the `overview` feature to work.
